import { Laptop, Monitor, Smartphone, TabletSmartphone } from 'lucide-react';
import { Device } from '@/types/Device';

export const BROWSER_ICONS = {
    chrome: '/media/icons/chrome.svg',
    firefox: '/media/icons/firefox.svg',
    safari: '/media/icons/safari.svg',
    edge: '/media/icons/edge.svg',
    opera: '/media/icons/opera.svg',
};

export const DEVICE_ICONS = {
    desktop: Monitor,
    laptop: Laptop,
    smartphone: Smartphone,
    tablet: TabletSmartphone,
};

export const DEVICES: Device[] = [
    {
        deviceType: 'desktop',
        deviceName: 'Mac',
        browser: 'chrome',
        browserIcon: BROWSER_ICONS['chrome'],
        os: 'MacOS',
        ip: '117.61.104.86',
        location: 'United States',
        added: '17 hours ago',
        lastSession: '16 Aug, 2024',
    },
    {
        deviceType: 'smartphone',
        deviceName: 'iPhone 12',
        browser: 'safari',
        browserIcon: BROWSER_ICONS['safari'],
        os: 'iOS',
        ip: '234.0.155.191',
        location: 'Canada',
        added: '2 days ago',
        lastSession: '15 Aug, 2024',
    },
    {
        deviceType: 'smartphone',
        deviceName: 'Samsung Galaxy S20',
        browser: 'chrome',
        browserIcon: BROWSER_ICONS['chrome'],
        os: 'Android',
        ip: '70.218.212.162',
        location: 'United Kingdom',
        added: '1 day ago',
        lastSession: '14 Aug, 2024',
    },
    {
        deviceType: 'tablet',
        deviceName: 'iPad Pro',
        browser: 'safari',
        browserIcon: BROWSER_ICONS['safari'],
        os: 'iOS',
        ip: '140.92.152.213',
        location: 'Australia',
        added: '3 days ago',
        lastSession: '13 Aug, 2024',
    },
    {
        deviceType: 'laptop',
        deviceName: 'Microsoft Surface 3',
        browser: 'edge',
        browserIcon: BROWSER_ICONS['edge'],
        os: 'Windows',
        ip: '214.219.147.46',
        location: 'Germany',
        added: '4 hours ago',
        lastSession: '12 Aug, 2024',
    },
    {
        deviceType: 'laptop',
        deviceName: 'Dell XPS',
        browser: 'chrome',
        browserIcon: BROWSER_ICONS['chrome'],
        os: 'Windows',
        ip: '246.44.68.100',
        location: 'France',
        added: '5 days ago',
        lastSession: '11 Aug, 2024',
    },
    {
        deviceType: 'smartphone',
        deviceName: 'Google Pixel 5',
        browser: 'chrome',
        browserIcon: BROWSER_ICONS['chrome'],
        os: 'Android',
        ip: '233.182.185.28',
        location: 'Japan',
        added: '6 days ago',
        lastSession: '10 Aug, 2024',
    },
    {
        deviceType: 'laptop',
        deviceName: 'MacBook Air',
        browser: 'safari',
        browserIcon: BROWSER_ICONS['safari'],
        os: 'MacOS',
        ip: '102.150.137.255',
        location: 'Italy',
        added: '8 hours ago',
        lastSession: '08 Aug, 2024',
    },
    {
        deviceType: 'smartphone',
        deviceName: 'Huawei P30',
        browser: 'chrome',
        browserIcon: BROWSER_ICONS['chrome'],
        os: 'Android',
        ip: '76.216.214.248',
        location: 'South Korea',
        added: '1 week ago',
        lastSession: '09 Aug, 2024',
    },
    {
        deviceType: 'smartphone',
        deviceName: 'Huawei P30',
        browser: 'chrome',
        browserIcon: BROWSER_ICONS['chrome'],
        os: 'Android',
        ip: '76.216.214.248',
        location: 'South Korea',
        added: '1 week ago',
        lastSession: '09 Aug, 2024',
    },
    {
        deviceType: 'smartphone',
        deviceName: 'Huawei P30',
        browser: 'chrome',
        browserIcon: BROWSER_ICONS['chrome'],
        os: 'Android',
        ip: '76.216.214.248',
        location: 'South Korea',
        added: '1 week ago',
        lastSession: '09 Aug, 2024',
    },
];
