// TODO: dynmically fetch features from stripe

export const feats = [
    {
        icon: "ki-graph",
        title: "Graph Visualization",
        subtitle: "seamlessly explore legal data",
        description: "Interactive graph displays relations and properties of case law and legislation",
        category: "search",
        plan: "freemium",
        link: "/features/graph-visualization",
    },
    {
        icon: "ki-price-tag",
        title: "Semantic Attributes",
        subtitle: "no more keyword search",
        description: "Obtain case law and legislation attrs with natural language queries",
        category: "search",
        plan: "freemium",
        link: "/features/semantic-attributes",
    },
    {
        icon: "ki-data",
        title: "Semantic Graph",
        subtitle: "find hidden ties in legal data",
        description: "Get entire text graph tree of legislation with natural language queries",
        category: "search",
        plan: "basic",
        link: "/features/semantic-graph",
    },
    {
        icon: "ki-abstract-26",
        title: "Full Semantic Search",
        subtitle: "top notch graph-vector query",
        description: "Graph relations and semantic results create a synergistic enrichment cycle",
        category: "search",
        plan: "advanced",
        link: "/features/full-semantic-search",
    },
    {
        icon: "ki-abstract-14",
        title: "Legal Breakdown",
        subtitle: "simplify complex legal data",
        description: "Decompose queries and extract concepts for precise legal answers",
        category: "query",
        plan: "freemium",
        link: "/features/legal-breakdown",
    },
    {
        icon: "ki-note-2",
        title: "Base Query",
        subtitle: "fast and easy response",
        description: "Get simple and accurate answers from GraphRAG-backed legal AI assistant",
        category: "query",
        plan: "basic",
        link: "/features/base-query",
    },
    {
        icon: "ki-book-open",
        title: "Advanced Query",
        subtitle: "delve deeper and broader",
        description: "Build complex queries with detailed legal analysis and stylized responses",
        category: "query",
        plan: "advanced",
        link: "/features/advanced-query",
    },
    {
        icon: "ki-artificial-intelligence",
        title: "Interactive Model",
        subtitle: "LLM asks for relevant data",
        description: "AI assistant identifies and fills critical domain-specific information gaps",
        category: "query",
        plan: "premium",
        link: "/features/interactive-model",
    },
    {
        icon: "ki-element-11",
        title: "Contexts Management",
        subtitle: "store and share legal sources",
        description: "Choose and control legal sources used by the AI assistant in queries",
        category: "storage",
        plan: "basic",
        link: "/features/contexts-management",
    },
    {
        icon: "ki-questionnaire-tablet",
        title: "Dossier Compilation",
        subtitle: "save and reuse valuable facts",
        description: "Manage and utilize project-specific legal data in a structured manner",
        category: "storage",
        plan: "advanced",
        link: "/features/dossier-compilation",
    },
    {
        icon: "ki-paper-clip",
        title: "Document Upload",
        subtitle: "analyse and use your docs",
        description: "Parse and decompose your legal documents for AI assistant queries",
        category: "storage",
        plan: "premium",
        link: "/features/document-upload",
    },
    {
        icon: "ki-cloud-download",
        title: "On-premises LLM",
        subtitle: "connect self-hosted LLMs",
        description: "Guard your data and connect your on-premises LLMs to our AI tools",
        category: "storage",
        plan: "premium",
        link: "/features/on-premises-llm",
    },
    {
        icon: "ki-chart-simple",
        title: "Base Analytics",
        subtitle: "gain insights from our data",
        description: "Analyze legal domain trends and patterns with predefined metrics",
        category: "analytics",
        plan: "advanced",
        link: "/features/base-analytics",
    },
    {
        icon: "ki-brifecase-tick",
        title: "Judicial Analytics",
        subtitle: "case law sentimental insights",
        description: "Analyze motivational trends in court decisions with chosen criteria",
        category: "analytics",
        plan: "premium",
        link: "/features/judicial-analytics",
    },
    {
        icon: "ki-chart",
        title: "Legislative Analytics",
        subtitle: "track law dynamic and usage",
        description: "Uncover historical and current law trends and their real-world impact",
        category: "analytics",
        plan: "premium",
        link: "/features/legislative-analytics",
    },
    {
        icon: "ki-chart-pie-3",
        title: "Full Analytics",
        subtitle: "panoramic view of law trends",
        description: "Synthesize analytics to uncover trends and forecast legal outcomes",
        category: "analytics",
        plan: "premium",
        link: "/features/full-analytics",
    },
];