name: Deploy Static Site

on:
    push:
        branches: ['main']
    workflow_dispatch:
        # Allow manual trigger

concurrency:
    group: prod-deploy
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node 22
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Configure AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ap-southeast-1

            - name: Set env
              run: |
                  echo "CLOUDFRONT_DISTRIBUTION_ID=E1KNCYS7QKEZ5Q" >> $GITHUB_ENV
                  echo "S3_BUCKET=s3://lexrag-site" >> $GITHUB_ENV
                  echo "CLOUDFRONT_DOMAIN=d26ppb9osin3vx.cloudfront.net" >> $GITHUB_ENV
                  echo "NEXT_PUBLIC_BASE_URL=https://lexrag.com" >> $GITHUB_ENV
                  echo "NEXT_PUBLIC_BASE_PATH=" >> $GITHUB_ENV
                  echo "NEXT_PUBLIC_APP_URL=https://app.lexrag.com" >> $GITHUB_ENV
                  echo "NEXT_PUBLIC_API_BASE_URL=https://api.lexrag.com" >> $GITHUB_ENV
                  echo "NEXT_PUBLIC_APP_SIGNUP_REDIRECT_PATH=/auth/email-verification" >> $GITHUB_ENV
                  echo "NEXT_PUBLIC_APP_SIGNIN_REDIRECT_PATH=/" >> $GITHUB_ENV
                  echo "NEXT_PUBLIC_SEGMENT_ENABLED=true" >> $GITHUB_ENV
                  echo "NEXT_PUBLIC_SEGMENT_DEBUG=false" >> $GITHUB_ENV
                  echo "NODE_ENV=production" >> $GITHUB_ENV

            - name: Install dependencies
              env:
                  NODE_ENV: ""
              run: npm ci --include=dev

            - name: Build
              env:
                  NEXT_PUBLIC_APP_URL: ${{ env.NEXT_PUBLIC_APP_URL }}
                  NEXT_PUBLIC_BASE_URL: ${{ env.NEXT_PUBLIC_BASE_URL }}
                  NEXT_PUBLIC_BASE_PATH: ${{ env.NEXT_PUBLIC_BASE_PATH }}
                  NEXT_PUBLIC_SEGMENT_ENABLED: ${{ env.NEXT_PUBLIC_SEGMENT_ENABLED }}
                  NEXT_PUBLIC_SEGMENT_WRITE_KEY: ${{ secrets.NEXT_PUBLIC_SEGMENT_WRITE_KEY }}
                  NEXT_PUBLIC_SEGMENT_DEBUG: ${{ env.NEXT_PUBLIC_SEGMENT_DEBUG }}
                  NEXT_PUBLIC_API_BASE_URL: ${{ env.NEXT_PUBLIC_API_BASE_URL }}
                  NEXT_PUBLIC_APP_SIGNUP_REDIRECT_PATH: ${{ env.NEXT_PUBLIC_APP_SIGNUP_REDIRECT_PATH }}
                  NEXT_PUBLIC_APP_SIGNIN_REDIRECT_PATH: ${{ env.NEXT_PUBLIC_APP_SIGNIN_REDIRECT_PATH }}
                  NODE_ENV: ${{ env.NODE_ENV }}
              run: npm run build

            - name: Deploy
              env:
                  DISTRIBUTION_ID: ${{ env.CLOUDFRONT_DISTRIBUTION_ID }}
                  S3_BUCKET: ${{ env.S3_BUCKET }}
                  NEXT_PUBLIC_APP_URL: ${{ env.NEXT_PUBLIC_APP_URL }}
                  NEXT_PUBLIC_BASE_URL: ${{ env.NEXT_PUBLIC_BASE_URL }}
                  NEXT_PUBLIC_BASE_PATH: ${{ env.NEXT_PUBLIC_BASE_PATH }}
                  NEXT_PUBLIC_SEGMENT_ENABLED: ${{ env.NEXT_PUBLIC_SEGMENT_ENABLED }}
                  NEXT_PUBLIC_SEGMENT_WRITE_KEY: ${{ secrets.NEXT_PUBLIC_SEGMENT_WRITE_KEY }}
                  NEXT_PUBLIC_SEGMENT_DEBUG: ${{ env.NEXT_PUBLIC_SEGMENT_DEBUG }}
                  NEXT_PUBLIC_API_BASE_URL: ${{ env.NEXT_PUBLIC_API_BASE_URL }}
                  NEXT_PUBLIC_APP_SIGNUP_REDIRECT_PATH: ${{ env.NEXT_PUBLIC_APP_SIGNUP_REDIRECT_PATH }}
                  NEXT_PUBLIC_APP_SIGNIN_REDIRECT_PATH: ${{ env.NEXT_PUBLIC_APP_SIGNIN_REDIRECT_PATH }}
                  NODE_ENV: ${{ env.NODE_ENV }}
              run: |
                  chmod +x scripts/deploy.sh
                  ./scripts/deploy.sh
